spring:
  datasource:
    url: jdbc:postgresql://postgres:${DB_PASS}@${DB_USER}:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        provider:
          google:
            issuer-uri: https://accounts.google.com
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/callback/google
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
